=== MahmoudDabbous/ITI-XML-Labs/lab 2/employee.dtd
<!DOCTYPE employees [
    <!ELEMENT employees (employee+)>
    <!ELEMENT employee (name, phones, addresses, email)>
    <!ATTLIST employee
        id ID #REQUIRED
    >
    <!ELEMENT name (first, last)>
    <!ELEMENT first (#PCDATA)>
    <!ELEMENT last (#PCDATA)>
    <!ELEMENT phones (phone+)>
    <!ELEMENT phone (#PCDATA)>
    <!ATTLIST phone
        type CDATA #REQUIRED
    >
    <!ELEMENT addresses (address)>
    <!ELEMENT address (City, Country)>
    <!ELEMENT City (#PCDATA)>
    <!ELEMENT Country (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
]>

=== MahmoudDabbous/ITI-XML-Labs/lab 1/Task1/employees.xml
<?xml version="1.0"?>
<!DOCTYPE employees SYSTEM "employee.dtd">
<?xml-stylesheet type="text/css" href="employee.css"?>
<employees>
    <employee id="1">
        <name>
            <first>Mahmoud</first>
            <last>Dabbous</last>
        </name>
        <phones>
            <phone type="home">004561237</phone>
            <phone type="work">002589631</phone>
            <phone type="mobile">01912345678</phone>
        </phones>
        <addresses>
            <address>
                <City>Alexandria</City>
                <Country>Eqypt</Country>
            </address>
        </addresses>
        <email>mahmoud@gmail.com</email>
    </employee>
    <employee id="2">
        <name>
            <first>Ahmed</first>
            <last>Galal</last>
        </name>
        <phones>
            <phone type="home">004561237</phone>
            <phone type="work">002589631</phone>
            <phone type="mobile">01912345678</phone>
        </phones>
        <addresses>
            <address>
                <City>Alexandria</City>
                <Country>Eqypt</Country>
            </address>
        </addresses>
        <email>mahmoud@gmail.com</email>
    </employee>
    <employee id="3">
        <name>
            <first>Mohammed</first>
            <last>Ali</last>
        </name>
        <phones>
            <phone type="home">004561237</phone>
            <phone type="work">002589631</phone>
            <phone type="mobile">01912345678</phone>
        </phones>
        <addresses>
            <address>
                <City>Alexandria</City>
                <Country>Eqypt</Country>
            </address>
        </addresses>
        <email>mahmoud@gmail.com</email>
    </employee>
</employees>
